CREATE TABLE PRODUCT(
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(20),
	price INT,
    regdate DATE,
    rate FLOAT
);

INSERT INTO PRODUCT VALUES (NULL, 'pants', 10000, SYSDATE(), 3.4);

SELECT * FROM PRODUCT;